# Titanic Dataset - Data Cleaning & Exploratory Data Analysis (EDA)
# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
titanic = sns.load_dataset("titanic")
print("First 5 rows:")
print(titanic.head())
print("\nDataset Info:")
print(titanic.info())
print("\nMissing values:")
print(titanic.isnull().sum())
titanic['age'] = titanic['age'].fillna(titanic['age'].median())
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])
titanic = titanic.drop(columns=['deck'])
sns.countplot(x="survived", data=titanic, palette="Set2")
plt.title("Survival Count")
plt.show()
sns.countplot(x="sex", hue="survived", data=titanic, palette="coolwarm")
plt.title("Survival by Gender")
plt.show()
sns.histplot(titanic['age'], kde=True, bins=30, color="skyblue")
plt.title("Age Distribution of Passengers")
plt.show()
sns.countplot(x="class", hue="survived", data=titanic, palette="muted")
plt.title("Survival by Passenger Class")
plt.show()
plt.figure(figsize=(10,6))
sns.heatmap(titanic.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()
print("Key Insights:")
print("- More males traveled than females, but females had higher survival rates.")
print("- Passengers in 1st class had better survival chances.")
print("- Younger passengers (children) had relatively higher survival rates.")
print("- Age and class are important factors for survival.")
